server:
  port: 9999
spring:
  application:
    name: boat-gateway
  cloud:
    nacos:
      discovery:
        # nacos注册中心-腾信云
        server-addr: 150.158.152.127:8848
    gateway:
      enabled: true
      discovery:
        locator:
          #开启gateway从nacos上获取服务列表
          enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        exclude: '*'